In [1]:
import pandas as pd

In [2]:
mylist = []
size = int(input('Enter the size of data you want to enter: '))
for x in range(0, size):
    value = int(input('Enter data: '))
    mylist.insert(x, value)
df = pd.DataFrame(mylist, columns=['X'])

Enter the size of data you want to enter: 10
Enter data: 15
Enter data: 56
Enter data: 59
Enter data: 75
Enter data: 14
Enter data: 25
Enter data: 90
Enter data: 12
Enter data: 25
Enter data: 35

In [3]:
def finddistance(c, enterlist, size):
    x = []
    for i in range(0, size):
        x.insert(i, abs(int(enterlist[i] - c)))
    return x

def condition(a, b):
    if a > b:
        return 'g'
    elif a < b:
        return 'l'
    elif a == b:
        return 'e'

import random
column = 'A'
previous = []
check2 = []
con = False
c1list = []
c2list = []
c1 = random.choice(mylist)
c2 = random.choice(mylist)
c1list = finddistance(c1, mylist, size)
c2list = finddistance(c2, mylist, size)
for i in range(0, size):
    if condition(c1list[i], c2list[i]) == 'g':
        check2.insert(i, '1')
    elif condition(c1list[i], c2list[i]) == 'l':
        check2.insert(i, '2')
    elif condition(c1list[i], c2list[i]) == 'e':
        check2.insert(i, '3')
previous = check2
df['C' + column + str(1)] = c1list
df['C' + column + str(2)] = c2list
column = chr(ord(column) + 1)
while True:
    c1list = []
    c2list = []
    c1 = random.choice(mylist)
    c2 = random.choice(mylist)
    c1list = finddistance(c1, mylist, size)
    c2list = finddistance(c2, mylist, size)
    check2 = []
    for i in range(0, size):
        if condition(c1list[i], c2list[i]) == 'g':
            check2.insert(i, '1')
        elif condition(c1list[i], c2list[i]) == 'l':
            check2.insert(i, '2')
        elif condition(c1list[i], c2list[i]) == 'e':
            check2.insert(i, '3')
    con = False
    for j in range(0, size):
        if previous[j] == '1' and check2[j] == '2':
            con = False
            break
        elif previous[j] == '2' and check2[j] == '1':
            con = False
            break
        elif previous[j] == '3' and check2[j] == '3':
            con = True
        elif previous[j] == '3' and check2[j] == '2':
            con = True
        elif previous[j] == '2' and check2[j] == '3':
            con = True
        elif previous[j] == '3' and check2[j] == '1':
            con = True
        elif previous[j] == '1' and check2[j] == '3':
            con = True
        elif previous[j] == check2[j]:
            con = True
    df['C' + column + str(1)] = c1list
    df['C' + column + str(2)] = c2list
    column = chr(ord(column) + 1)
    if column == 'Z':
        column = 'A'
    if con == True:
        break
    previous = check2

In [4]:
df

    X  CA1  CA2  CB1  CB2
0  15   75   75    0   10
1  56   34   34   41   31
2  59   31   31   44   34
3  75   15   15   60   50
4  14   76   76    1   11
5  25   65   65   10    0
6  90    0    0   75   65
7  12   78   78    3   13
8  25   65   65   10    0
9  35   55   55   20   10